export type TNowAir = {
  so2Grade: string;
  coFlag: string | null;
  khaiValue: string;
  so2Value: string;
  coValue: string;
  pm25Flag: string | null;
  pm10Flag: string | null;
  o3Grade: string;
  pm10Value: string;
  khaiGrade: string;
  pm25Value: string;
  sidoName: string;
  no2Flag: string | null;
  no2Grade: string;
  o3Flag: string | null;
  pm25Grade: string;
  so2Flag: string | null;
  dataTime: string;
  coGrade: string;
  no2Value: string;
  stationName: string;
  pm10Grade: string;
  o3Value: string;
  pm25Grade1h: string;
  pm10Value24: string;
  pm10Grade1h: string;
  mangName: string;
  pm25Value24: string;
};
